package com.claudej.domain.common.exception;

public enum ErrorCode {

    INVALID_SHORT_CODE("INVALID_SHORT_CODE", "无效的短链码"),

    // Cart Management
    CART_NOT_FOUND("CART_NOT_FOUND", "购物车不存在"),
    CART_ITEM_NOT_FOUND("CART_ITEM_NOT_FOUND", "购物车商品不存在"),
    CART_ITEM_QUANTITY_INVALID("CART_ITEM_QUANTITY_INVALID", "商品数量必须在1-999之间"),
    CART_MONEY_AMOUNT_NULL("CART_MONEY_AMOUNT_NULL", "金额不能为空"),
    CART_MONEY_AMOUNT_NEGATIVE("CART_MONEY_AMOUNT_NEGATIVE", "金额不能为负数"),
    CART_MONEY_CURRENCY_EMPTY("CART_MONEY_CURRENCY_EMPTY", "币种不能为空"),
    CART_CURRENCY_MISMATCH("CART_CURRENCY_MISMATCH", "币种不一致"),
    CART_USER_ID_EMPTY("CART_USER_ID_EMPTY", "用户ID不能为空"),
    CART_PRODUCT_ID_EMPTY("CART_PRODUCT_ID_EMPTY", "商品ID不能为空"),
    INVALID_ORIGINAL_URL("INVALID_ORIGINAL_URL", "无效的原始URL"),
    SHORT_LINK_NOT_FOUND("SHORT_LINK_NOT_FOUND", "短链接不存在"),
    SHORT_CODE_ALREADY_ASSIGNED("SHORT_CODE_ALREADY_ASSIGNED", "短链码已分配"),
    SHORT_LINK_EXPIRED("SHORT_LINK_EXPIRED", "短链接已过期"),

    // Link Management
    LINK_NOT_FOUND("LINK_NOT_FOUND", "链接不存在"),
    LINK_NAME_EMPTY("LINK_NAME_EMPTY", "链接名称不能为空"),
    LINK_NAME_TOO_LONG("LINK_NAME_TOO_LONG", "链接名称长度不能超过100"),
    LINK_URL_EMPTY("LINK_URL_EMPTY", "链接地址不能为空"),
    LINK_URL_TOO_LONG("LINK_URL_TOO_LONG", "链接地址长度不能超过500"),
    LINK_URL_INVALID("LINK_URL_INVALID", "链接地址格式无效"),

    // Order Management
    ORDER_NOT_FOUND("ORDER_NOT_FOUND", "订单不存在"),
    ORDER_ITEM_QUANTITY_INVALID("ORDER_ITEM_QUANTITY_INVALID", "订单项数量必须大于0"),
    ORDER_ITEM_PRICE_INVALID("ORDER_ITEM_PRICE_INVALID", "订单项单价不能为负"),
    ORDER_ALREADY_PAID("ORDER_ALREADY_PAID", "订单已支付"),
    ORDER_NOT_PAID("ORDER_NOT_PAID", "订单未支付"),
    ORDER_ALREADY_SHIPPED("ORDER_ALREADY_SHIPPED", "订单已发货"),
    ORDER_ALREADY_DELIVERED("ORDER_ALREADY_DELIVERED", "订单已送达"),
    ORDER_ALREADY_CANCELLED("ORDER_ALREADY_CANCELLED", "订单已取消"),
    ORDER_CANNOT_CANCEL("ORDER_CANNOT_CANCEL", "订单状态不允许取消"),
    INVALID_ORDER_STATUS_TRANSITION("INVALID_ORDER_STATUS_TRANSITION", "无效的订单状态转换"),
    MONEY_AMOUNT_NEGATIVE("MONEY_AMOUNT_NEGATIVE", "金额不能为负数"),
    MONEY_CURRENCY_EMPTY("MONEY_CURRENCY_EMPTY", "币种不能为空"),

    // User Management
    USER_NOT_FOUND("USER_NOT_FOUND", "用户不存在"),
    USERNAME_ALREADY_EXISTS("USERNAME_ALREADY_EXISTS", "用户名已存在"),
    INVALID_USERNAME("INVALID_USERNAME", "用户名格式无效，应为2-20字符"),
    INVALID_EMAIL("INVALID_EMAIL", "邮箱格式无效"),
    INVALID_PHONE("INVALID_PHONE", "手机号格式无效，应为11位数字"),
    INVALID_INVITE_CODE("INVALID_INVITE_CODE", "无效的邀请码"),
    INVITE_CODE_ALREADY_EXISTS("INVITE_CODE_ALREADY_EXISTS", "邀请码已存在"),
    INVALID_USER_STATUS_TRANSITION("INVALID_USER_STATUS_TRANSITION", "无效的用户状态转换"),

    // Coupon Management
    COUPON_NOT_FOUND("COUPON_NOT_FOUND", "优惠券不存在"),
    COUPON_ID_EMPTY("COUPON_ID_EMPTY", "优惠券ID不能为空"),
    COUPON_NAME_EMPTY("COUPON_NAME_EMPTY", "优惠券名称不能为空"),
    COUPON_NAME_TOO_LONG("COUPON_NAME_TOO_LONG", "优惠券名称长度不能超过50"),
    COUPON_DISCOUNT_VALUE_INVALID("COUPON_DISCOUNT_VALUE_INVALID", "折扣值无效"),
    COUPON_MIN_ORDER_AMOUNT_INVALID("COUPON_MIN_ORDER_AMOUNT_INVALID", "最低订单金额无效"),
    COUPON_USER_ID_EMPTY("COUPON_USER_ID_EMPTY", "用户ID不能为空"),
    COUPON_VALIDITY_INVALID("COUPON_VALIDITY_INVALID", "有效期无效"),
    COUPON_NOT_YET_VALID("COUPON_NOT_YET_VALID", "优惠券尚未生效"),
    COUPON_ORDER_ID_EMPTY("COUPON_ORDER_ID_EMPTY", "订单号不能为空"),
    INVALID_COUPON_STATUS_TRANSITION("INVALID_COUPON_STATUS_TRANSITION", "无效的优惠券状态转换");

    private final String code;
    private final String message;

    ErrorCode(String code, String message) {
        this.code = code;
        this.message = message;
    }

    public String getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}
